name: Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - name: Install minimal stable
      uses: dtolnay/rust-toolchain@stable 
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install cargo nextest
      uses: taiki-e/install-action@nextest
    - name: Build and archive tests
      run: cargo nextest archive --archive-file nextest-archive.tar.zst
    - name: Upload archive to workflow
      uses: actions/upload-artifact@v3
      with:
        name: nextest-archive-${{ matrix.os }}
        path: nextest-archive-${{ matrix.os }}.tar.zst
    
  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        partition: [ 1, 2 ]

    steps:
    - name: Run tests
      run: cargo nextest run --workspace --profile ci --partition hash:${{ matrix.partition }}/2
    # nextest does not require cargo to run the tests, instead, create ~/.cargo/bin required by install action.
    - run: mkdir -p ~/.cargo/bin
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - name: Download archive
      uses: actions/download-artifact@v3
      with:
        name: nextest-archive-${{ matrix.os }}
    - name: Run tests
      # Profile "ci" is configured in .config/nextest.toml
      run: |
        ~/.cargo/bin/cargo-nextest nextest run --archive-file nextest-archive${{ matrix.os }}.tar.zst \
          --partition hash:${{ matrix.partition }}/2
